on:
  pull_request:
  issue_comment:
    types: [created]

jobs:
  go963:
    runs-on: ubuntu-18.04
    name: go963
    env:
      GO963_SECRETFILE: ${{ secrets.GO963_SECRETFILE }}
      GO963_CACHETOKENFILE: ${{ secrets.GO963_CACHETOKENFILE }}
    steps:
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - uses: actions/checkout@master
    - name: Decrypt large secret
      run: ./.github/scripts/decrypt_secret.sh
      env:
        LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}
    - id: go963
      uses: docker://srzzumix/go963
      env:
        GO963_CALENDARID: ${{ secrets.GO963_CALENDARID }}
      with:
        args: help
    - name: go963 success message
      uses: actions/github-script@0.9.0
      if: steps.go963.outputs.exitcode == 0
      env:
        STDOUT: "```${{ steps.go963.outputs.stdout }}```"
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: "#### `go963` Success\n" + process.env.STDOUT
          })
